name: CI
on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:

jobs:
  archive:
    name: Archive Ckt
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive
        run: tar -cvf ieee37.ckt *.csv README LICENSE
      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: ckt
          path: ieee37.ckt

  release:
    name: Release
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    permissions: write-all
    needs: [ archive ]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ckt

      - name: Release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Ckv artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ieee37.ckt
          asset_name: ieee37-${{ github.ref_name }}.ckt
          asset_content_type: application/x-tar
